### ISSUE TITLE
我是 yoga14s 5800h 用您的方法修复micphone失败

### ISSUE THREAD

**Issue by Kanepan** [koyangyang/Lenovo-Yoga-14S-2020ARE-hackintosh#1]
看了 layout都是21，请问4800h版的声卡是 acl 287 吗？

**Comment by ccoz** [comment]
首先你要在win下看你的microphone是不是AMD的，如果是AMD的话可以安装我的教程修复。如果你不是AMD的，可以试试用HDA的方式修复

**Comment by Kanepan** [comment]
> 首先你要在win下看你的microphone是不是AMD的，如果是AMD的话可以安装我的教程修复。如果你不是AMD的，可以试试用HDA的方式修复

感谢， 我怕对音质有损失，最终还是买了 usb无驱的mic

**Comment by ccoz** [comment]
我用AMDMicrophone修复的自带麦克风和3.5mm的麦克风都没问题，开过几次会议，没有感觉音质有啥大问题。但是HDA驱动就不太清楚，自行测试。
