### ISSUE TITLE
Nootedred 作者又更新了， 现在很丝滑。 就剩一个 硬解问题了。

### ISSUE THREAD

**Issue by Kanepan** [koyangyang/Lenovo-Yoga-14S-2020ARE-hackintosh#2]
Nootedred 作者又更新了， 现在很丝滑。 就剩一个 硬解问题了。

**Comment by koyangyang** [comment]
我自己用上了，现在还未上传，等会更新

**Comment by ccoz** [comment]
我自己已经用了几天，现在还未上传，等会更新~

**Comment by Kanepan** [comment]
up发现没有，CPU性能都有提示。 我的geekbench 和 cinebench都提高了20%

**Comment by ccoz** [comment]
更新提升还是很大，但是硬解功能还是没有上，一起一正式版为准，期待！

**Comment by lajidonggua** [comment]
睡眠解决了吗

**Comment by ccoz** [comment]
睡眠问题有很多原因导致，但是感觉4000系希望不大，5000系倒是有人睡眠正常
