### ISSUE TITLE
蓝牙搜索不到

### ISSUE THREAD

**Issue by lajidonggua** [koyangyang/Lenovo-Yoga-14S-2020ARE-hackintosh#3]

**Comment by ccoz** [comment]
已修复，更新最新13.4的EFI,测试一下是否有效

**Comment by lajidonggua** [comment]
好的，谢谢

**Comment by lajidonggua** [comment]
我发现 好像要什么都不插， 开机就会两个都有，要是xhc0 有东西， xhc1就会失效， xhc1 有东西， xhc0就会失效， 你的会吗

**Comment by lajidonggua** [comment]
哦哦，现在发现好像是随机的。。我复现不了情况

**Comment by ccoz** [comment]
> 我发现 好像要什么都不插， 开机就会两个都有，要是xhc0 有东西， xhc1就会失效， xhc1 有东西， xhc0就会失效， 你的会吗

没见过这个情况，我每次开机xhc0都插有鼠标。可能使用EFI后需要重新对本电脑进行定制USB。

**Comment by lajidonggua** [comment]
> > 我发现 好像要什么都不插， 开机就会两个都有，要是xhc0 有东西， xhc1就会失效， xhc1 有东西， xhc0就会失效， 你的会吗
> 
> 没见过这个情况，我每次开机xhc0都插有鼠标。可能使用EFI后需要重新对本电脑进行定制USB。

谢谢回复，我去定制试试

**Comment by lajidonggua** [comment]
还是不行。。。

**Comment by ccoz** [comment]
这个蓝牙问题是随机性的，我问了一些使用的人，我认为最可能的原因的USB定制问题，最好根据自己机型重新定制USB。我现在已经换到Intel平台了，目前AMD平台无法硬解让我很难接受，我暂时停止维护了，当然也欢迎正在使用的朋友解决问题后PR。
